# Generated by Django 2.2.3 on 2020-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='stripe_user_id',
            field=models.TextField(blank=True),
        ),
    ]
