# Generated by Django 2.2.3 on 2020-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_manager_stripe_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='card_number',
            field=models.TextField(blank=True),
        ),
    ]
