# Generated by Django 2.2.3 on 2020-07-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_manager_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='sub_date',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='sub_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='sub_name',
            field=models.TextField(blank=True),
        ),
    ]
