# Generated by Django 2.2.3 on 2020-07-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200726_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='sub_id',
            field=models.TextField(blank=True),
        ),
    ]
