# Generated by Django 2.2.3 on 2020-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_manager_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='product_id',
            field=models.TextField(blank=True),
        ),
    ]
