# Generated by Django 2.2.3 on 2020-07-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_manager_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('subscription_name', models.TextField()),
                ('subscription_id', models.TextField()),
                ('subscription_purchase_on', models.TextField()),
                ('subscription_status', models.TextField()),
                ('subscription_ended_on', models.TextField()),
            ],
        ),
    ]
